version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hrovice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Bilel1998
    ports:
      - 5432
  web: 
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
